# Generated by Django 3.0 on 2022-08-22 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_auto_20220822_1131'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
